services:
  yapyapyap-db:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  flyway:
    image: flyway/flyway
    command: -postgresql.transactional.lock=false -url=jdbc:postgresql://yapyapyap-db:5432/postgres -user=postgres -password=postgres -connectRetriesInterval=60 -connectRetries=120 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - yapyapyap-db
  yapyapyap-auth:
    build: ./auth
    ports:
      - 3333:3333
    depends_on:
      - yapyapyap-db
  yapyapyap-message:
    build: ./message
    ports:
      - 3334:3333
    depends_on:
      - yapyapyap-db
  yapyapyap-zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/yapyapyap"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  yapyapyap-kafka:
    image: docker.io/bitnami/kafka:3.4
    deploy:
        replicas: 3
    ports:
      - 9092-9095:9092
    volumes:
      - "kafka_data:/yapyapyap"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=yapyapyap-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - yapyapyap-zookeeper
  yapyapyap-message-writer:
    build: ./message-writer
    deploy:
      replicas: 3
    depends_on:
      - yapyapyap-db
      - yapyapyap-kafka
      - yapyapyap-zookeeper
  yapyapyap-hub:
    build: ./proxchat-hub
    deploy:
        replicas: 3
    ports:
      - 9005-9008:9001
    depends_on:
      - yapyapyap-db
      - yapyapyap-kafka
      - yapyapyap-zookeeper
      - yapyapyap-message-writer

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local